//---------------------------------------------------------------------------

#ifndef U1H
#define U1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
	TPanel *Panel1;
	TButton *Button1;
	TEdit *Edit1;
	TMemo *Memo1;
	TButton *Button2;
	TComboBox *ComboBox1;
	TLabel *Label1;
	TLabel *Label2;
     TEdit *Edit2;
     TEdit *Edit3;
     TButton *Button3;
     TButton *Button4;
     TTimer *Timer1;
        TImage *Image1;
        TImage *Image2;
        TImage *Image3;
        TImage *Image4;
        TImage *Image5;
        TImage *Image6;
        TImage *Image7;
        TImage *Image8;
        TImage *Image9;
        TImage *Image10;
        TImage *Image11;
        TImage *Image12;
        TImage *Image13;
        TImage *Image14;
        TImage *Image15;
        TImage *Image16;
        TLabel *Label3;
        TImage *Image17;
        TImage *Image18;
        TImage *Image19;
        TImage *Image20;
        TImage *Image21;
        TImage *Image22;
        TImage *Image23;
        TImage *Image24;
        TImage *Image25;
        TImage *Image26;
        TImage *Image27;
        TImage *Image28;
        TImage *Image29;
        TImage *Image30;
        TImage *Image31;
        TImage *Image32;
        TLabel *Label4;
        TImage *Image33;
        TImage *Image34;
        TImage *Image35;
        TImage *Image36;
        TImage *Image37;
        TImage *Image38;
        TImage *Image39;
        TImage *Image40;
        TImage *Image41;
        TImage *Image42;
        TImage *Image43;
        TImage *Image44;
        TImage *Image45;
        TImage *Image46;
        TImage *Image47;
        TImage *Image48;
        TLabel *Label5;
        TImage *Image49;
        TImage *Image50;
        TImage *Image51;
        TImage *Image52;
        TImage *Image53;
        TImage *Image54;
        TImage *Image55;
        TImage *Image56;
        TImage *Image57;
        TImage *Image58;
        TImage *Image59;
        TImage *Image60;
        TImage *Image61;
        TImage *Image62;
        TImage *Image63;
        TImage *Image64;
        TLabel *Label6;
        TImage *Image65;
        TImage *Image66;
        TImage *Image67;
        TImage *Image68;
        TImage *Image69;
        TImage *Image70;
        TImage *Image71;
        TImage *Image72;
        TImage *Image73;
        TImage *Image74;
        TImage *Image75;
        TImage *Image76;
        TImage *Image77;
        TImage *Image78;
        TImage *Image79;
        TImage *Image80;
        TLabel *Label7;
        TImage *Image81;
        TImage *Image82;
        TImage *Image83;
        TImage *Image84;
        TImage *Image85;
        TImage *Image86;
        TImage *Image87;
        TImage *Image88;
        TImage *Image89;
        TImage *Image90;
        TImage *Image91;
        TImage *Image92;
        TImage *Image93;
        TImage *Image94;
        TImage *Image95;
        TImage *Image96;
        TLabel *Label8;
        TImage *Image97;
        TImage *Image98;
        TImage *Image99;
        TImage *Image100;
        TImage *Image101;
        TImage *Image102;
        TImage *Image103;
        TImage *Image104;
        TImage *Image105;
        TImage *Image106;
        TImage *Image107;
        TImage *Image108;
        TImage *Image109;
        TImage *Image110;
        TImage *Image111;
        TImage *Image112;
        TLabel *Label9;
        TImage *Image113;
        TImage *Image114;
        TImage *Image115;
        TImage *Image116;
        TImage *Image117;
        TImage *Image118;
        TImage *Image119;
        TImage *Image120;
        TImage *Image121;
        TImage *Image122;
        TImage *Image123;
        TImage *Image124;
        TImage *Image125;
        TImage *Image126;
        TImage *Image127;
        TImage *Image128;
        TLabel *Label10;
        TImage *Image129;
        TImage *Image130;
        TImage *Image131;
        TImage *Image132;
        TImage *Image133;
        TImage *Image134;
        TImage *Image135;
        TImage *Image136;
        TImage *Image137;
        TImage *Image138;
        TImage *Image139;
        TImage *Image140;
        TImage *Image141;
        TImage *Image142;
        TImage *Image143;
        TImage *Image144;
        TLabel *Label11;
        TImage *Image145;
        TImage *Image146;
        TImage *Image147;
        TImage *Image148;
        TImage *Image149;
        TImage *Image150;
        TImage *Image151;
        TImage *Image152;
        TImage *Image153;
        TImage *Image154;
        TImage *Image155;
        TImage *Image156;
        TImage *Image157;
        TImage *Image158;
        TImage *Image159;
        TImage *Image160;
   	void __fastcall Button1Click(TObject *Sender);
	void __fastcall Image1Click(TObject *Sender);
	void __fastcall Button2Click(TObject *Sender);
     void __fastcall Edit1Change(TObject *Sender);
     void __fastcall ComboBox1Change(TObject *Sender);
     void __fastcall Button3Click(TObject *Sender);
     void __fastcall Button4Click(TObject *Sender);
     void __fastcall Timer1Timer(TObject *Sender);
     void __fastcall Edit2Change(TObject *Sender);
private:	// User declarations
public:		// User declarations
	__fastcall TForm1(TComponent* Owner);
     void __fastcall TForm1::qwads_drow(void);
     void __fastcall TForm1::line_text_create(void);
     void __fastcall TForm1::array_create(void);
     void __fastcall TForm1::vert_create(void);
     void __fastcall TForm1::horiz_create(void);
     void __fastcall TForm1::string_create(void);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
